config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :courses
  devise_for :users, :controllers => { :registrations => "registrations" }, :path_prefix => 'd'
  resources :students do
    post :print_selected, :on => :collection
  end
  root 'students#index'
  match '/users',   to: 'users#index',   via: 'get'
  resources :users
  resources :student_imports

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
    #attr_accessor :image, :remote_image_url
    belongs_to :user
    belongs_to :course # course id in school table

    #for image validation
    #mount_uploader :image, ImageUploader
    #validates_processing_of :image
    #validate :image_size_validation

    #form field validation
    validates :name, presence: true, length: {maximum: 255}, format: { :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/, message: "may only contain letters and numbers." }
    validates :code,  presence: true

    #simple search form
    def self.search(search)
        if search.present? 
            where('user_id = ?', search)
        else
            all   
        end
    end

    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
          csv << column_names
          all.each do |student|
            csv << student.attributes.values_at(*column_names)
          end
        end
      end

    #private
    #def image_size_validation
     #   errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
    #end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  # GET /students
  # GET /students.json
  def index
    if current_user.admin?
      if params[:user_id]
        @students = Student.search(params[:user_id])
      end
        @students = Student.search(params[:user_id] )
        respond_to do |format|
          format.html
          format.csv { send_data @students.to_csv }
          format.xls  #{ send_data @products.to_csv(col_sep: "\t") }
        end
    else
      @students = Student.search(params[:search]).where(user_id: current_user.id)
      render :user_index
    end
  end

  def print_selected
    params[:ids].each do |id|
      student = Student.find(id)
      student.destroy
    end unless params[:ids].blank?
    redirect_to students_url, :notice => 'Selected student are deleted successfully!'
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])
    if current_user.admin?
      @student.update_attributes(status: 'complete')
      @student.save!
    end
    respond_to do |format|
      format.html
      format.json { head :no_content }
      format.pdf do
        pdf = StudentPdf.new(@student)
        send_data pdf.render,
                  filename: "student_#{@student.name}",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  # GET /students/new
  def new
    @student = current_user.students.build(status: 'imcomplete')
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = current_user.students.build(student_params)
    @student.status = 'imcomplete'
    respond_to do |format|
      if @student.save
        format.html { redirect_to students_url, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to students_url, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:code, :name, :course_id, :user_id)
    end
    #add sortable format
    def sort_column
      Student.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class="row">
  <div class="col-md-6 col-xs-6 col-md-offset-3">
    <%= form_with(model: student, local: true) do |form| %>
      <% if student.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(student.errors.count, "error") %> error for  this student from being saved:</h2>

          <ul>
          <% student.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :code %>
        <%= form.text_field :code, id: :student_code %>
      </div>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :student_name %>
      </div>

      <div class="field">
        <%= form.label :course %>
        <% if current_user.admin? %>
          <%= form.select :course_id, Course.all.map{ |c| [c.title, c.id]}, {:prompt => "select"}%>
        <% else %>
          <%= form.select :course_id, options_from_collection_for_select(current_user.courses.all, 'id', 'title'), id: "course_id" %>
        <% end %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/students/admin_index.html.erb
<h1>All Students</h1>
<%= link_to 'New Student', new_student_path, class: "btn btn-primary" %>

<table id="student" class="table table-hover">
  <thead>
    <tr>
      <th><input type="checkbox" id="selectall"/></th>
      <th>Student Code</th>
      <th>Student Name</th>
      <th>Course</th>
      <th>Created Time</th>
      <th>Updated Time</th>
      
      <th>
        <%= form_tag students_path, :method => 'get', :id => "user_select" do %>
          <%= select_tag :user_id, options_from_collection_for_select(User.all, 'id', 'name'), id: "user_select", onchange: 'this.form.submit();', prompt: "User" %>
        <% end %>
      </th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
      
    </tr>
  </thead>

  <tbody>
    
    <% @students.each do |student| %>
      <tr>
        <td><%= check_box_tag "student_id[]", student.id %></td>
        <td><%= student.code %></td>
        <td><%= student.name %></td>
        <td><%= student.course.name %></td>
        <td> <%= student.created_at %></td>
        <td><%= student.updated_at%> </td>
        <td><%= student.user.name %></td>
        <td><%= student.status%> </td>
        <td><%= link_to "Print", student_path(student, format: 'pdf'), class: "btn btn-default btn btn-info"%></td>
        <td><%= link_to 'Edit', edit_student_path(student), class: "btn btn-default btn btn-success" %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= javascript_tag do %>
  $(document).ready(function() {
    $('#student').dataTable();
} );
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path, class: "btn btn-default btn-float btn-cancel" %>

app/views/students/index.html.erb
<h1>All Students</h1>
<%= link_to 'New Student', new_student_path, class: "btn btn-primary" %>
<span>
<%= link_to "Import", new_student_import_path, class: "btn btn-primary" %>
<%= link_to "Export", students_path(format: "csv"), class: "btn btn-primary"  %>
</span>
<table id="student" class="table table-hover">
  <thead>
    <tr>
      <th><input type="checkbox" id="selectall"/></th>
      <th>Student Code</th>
      <th>Student Name</th>
      <th>Course</th>
      <th>Created Time</th>
      <th>Updated Time</th>
      
      <th>
        <%= form_tag students_path, :method => 'get', :id => "user_select" do %>
          <%= select_tag :user_id, options_from_collection_for_select(User.all, 'id', 'name'), id: "user_select", onchange: 'this.form.submit();', prompt: "User" %>
        <% end %>
      </th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
      
    </tr>
  </thead>

  <tbody>
    
    <% @students.each do |student| %>
      <tr>
        <td><%= check_box_tag "student_id[]", student.id %></td>
        <td><%= student.code %></td>
        <td><%= student.name %></td>
        <td><%= student.course.name %></td>
        <td> <%= student.created_at %></td>
        <td><%= student.updated_at%> </td>
        <td><%= student.user.name %></td>
        <td><%= student.status%> </td>
        <td><%= link_to "Print", student_path(student, format: 'pdf'), class: "btn btn-default btn btn-info"%></td>
        <td><%= link_to 'Edit', edit_student_path(student), class: "btn btn-default btn btn-success" %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= javascript_tag do %>
  $(document).ready(function() {
    $('#student').dataTable();
} );
<% end %>

app/views/students/new.html.erb
<h1>New Student</h1>

 <%= render 'form', student: @student %>
 
<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<h1>Student Information</h1>
<div class="row">
  <div class="col-md-6 col-xs-6 col-md-offset-3">
    <p id="notice"><%= notice %></p>

    <dl class="dl-horizontal">
      <dt>Student Code:</dt>
      <dd><%= @student.code %></dd>
    </dl>

    <dl class="dl-horizontal">
      <dt>Student Name:</dt>
      <dd><%= @student.name %></dd>
    </dl>

    <dl class="dl-horizontal">
      <dt>Email:</dt>
      <dd><%= @student.user.email %></dd>
    </dl>

    <dl class="dl-horizontal">
      <dt>Course:</dt>
      <dd><%= @student.course.name %></dd>
    </dl>

    <%= link_to 'Back', students_path, class: "btn btn-default btn-float btn-cancel"  %>
    <% if current_user.admin? %>
       <%= link_to "Print(PDF)", student_path(@student, format: 'pdf'), class: "btn btn-default btn-float btn-cancel"  %>
    <% end %>
  </div>
</div>

app/views/students/user_index.html.erb
<h1>All Students</h1>
<%= link_to 'New Student', new_student_path, class: "btn btn-primary" %>
<table id="student" class="table table-hover">
  <thead>
    <tr>
      <th>Student Code</th>
      <th>Student Name</th>
      <th>Course</th>
      <th>created_at</th>
      <th>updated_at</th>
      <th>status</th>
      <th></th>
      <th></th>
      <th></th>
      
    </tr>
  </thead>

  <tbody>
    
    <% @students.each do |student| %>
      <tr>
        <td><%= student.code %></td>
        <td><%= student.name %></td>
        <td><%= student.course.name %></td>
        <td> <%= student.created_at %></td>
        <td><%= student.updated_at%> </td>
        <td><%= student.status%> </td>
        <td><%= link_to 'Show', student, class: "btn btn-default btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_student_path(student), class: "btn btn-default btn-float btn btn-success" %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= javascript_tag do %>
  $(document).ready(function() {
    $('#student').dataTable();
} );
<% end %>