config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :courses
  devise_for :users, :controllers => { :registrations => "registrations" }, :path_prefix => 'd'
  resources :students do
    post :print_selected, :on => :collection
  end
  root 'students#index'
  match '/users',   to: 'users#index',   via: 'get'
  resources :users
  resources :student_imports

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="text-center">
   <a href="http://www.railstutorial.org/">Created By Sgswteam</a>
   </div>
  
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <%= link_to "Attendence", root_path, id: "logo",  class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        
       <li><%= link_to 'Students', students_path %></li>
       <li><%= link_to 'Courses', courses_path %></li>
       <li><%= link_to 'Users', users_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"> <%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit", edit_user_registration_path %></li>
            <li class="divider"></li>
              <li>
                <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
              </li>
          </ul>
        </li>
        <% else %>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Attendence</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %> <!--  error msg from signup -->
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  
  </body>
</html>